name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: GonzaloFernandez20
          output: dist/github-contribution-grid-snake.svg # Asegúrate de que esta ruta sea correcta

      - name: Commit and push snake animation
        run: |
          git config --local user.email "gonzalo007fernandez@gmail.com
          git config --local user.name "Gonzalo Fernandez"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push